name: Deploy

on:
  push:
    branches: [ v2 ]
  workflow_dispatch:

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - name: Install Bun
          run: |
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> $GITHUB_PATH
        - name: Check Bun
          run: bun --version
        - name: Install Dependencies
          run: bun install
        - name: Build Website
          run: bun run build
        - name: Install SSH key
          uses: https://github.com/shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.DEPLOY_KEY }}
            name: id_ed25519
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
            if_key_exists: replace
        - name: Install rSync
          run: |
              sudo apt-get update
              sudo apt-get install -y rsync
        - name: Copy build output and commit
          run: |
              git clone ${{ vars.DEPLOY_REPOSITORY }} _deploy
              rsync -av --delete dist/ _deploy/
              cd _deploy
              ls -a
              git config user.email "ci@oriondev.fr"
              git config user.name "Forgejo CI"
              git add .
              git commit -m "deploy: $(date -u +%Y-%m-%dT%H:%M:%SZ) @ ${{ github.sha }}" || exit 0
              # git push
