name: Deploy

on:
  push:
    branches: [ v2 ]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - run: bun install
        - run: bun run build
        - name: Deploy via SSH
          uses: https://github.com/appleboy/scp-action@v1.0.0
          with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.DEPLOY_KEY }}
              source: "dist/*"
              target: "/srv/oriondev.fr"
