name: Deploy

on:
  push:
    branches: [ v2 ]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - name: Install Bun
          run: |
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> $GITHUB_PATH
        - name: Check Bun
          run: bun --version
        - run: bun install
        - run: bun run build
        - name: Deploy via SSH
          uses: https://github.com/appleboy/scp-action@v1.0.0
          with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.DEPLOY_KEY }}
              source: "dist/*"
              target: "/srv/oriondev.fr"
              debug: true
